sudo: false
language: node_js

node_js:
- "4.0"
- "4"
- "5"

install:
  - npm install
  - npm install hapi joi boom
  - npm install -g codeclimate-test-reporter codecov

script:
  - npm run lint
  - npm run test:cov
  - npm run build

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - codecov
